### ISSUE TITLE
Bump versioncode

### ISSUE THREAD

**Issue by ghost** [MrFlyingToasterman/Pijaret#1]
Versionname is a string without any other function than that, a name. The actual version is the versioncode, an integer that should get bumped with each release. Android considers a version 1.4 (1) and a version 1.3 (1) the same. See https://developer.android.com/studio/publish/versioning.html

**Comment by MrFlyingToasterman** [comment]
`defaultConfig {
        applicationId "dmusiolik.pijaret"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 4
        versionName "1.4"
}`

I changed versionCode from 1 to 4. Thanks for the information i'll mind that in the future.

**Comment by ghost** [comment]
Thanks for the quick fix!
