### ISSUE TITLE
Add a warning about the extremely weak encryption

### ISSUE THREAD

**Issue by tdelmas** [MrFlyingToasterman/Pijaret#2]
If the size of the key is less than the total size of all encrypted message with that key, it's really easy to recover the key from an encrypted message.

**Comment by aplufr** [comment]
Rot algorithm are extremely weak no matter the key size you use. The only difference with classic [Caesar](https://en.wikipedia.org/wiki/Caesar_cipher#Breaking_the_cipher) is that it seem we are using the whole Unicode table here.. but this does not remove frequency analysis weakness and brute-forcing to decrypt.

(and IMO in 2016 when we are looking for weakness in AES, Chacha and others block cipher, this app only add illusion of security)

**Comment by MrFlyingToasterman** [comment]
Of course its not that secure! Pijaret is just a small cipher and not for serious prurpose.
Please see my Schoolwork as a Toycrypter.

I added a warning for a password less than 4 numbers but i'll soon add a new warning to make clear Pijaret is a Toycrypter!

**Comment by tdelmas** [comment]
@mulx +1

@MrFlyingToasterman thanks. It's really not obvious (for non-tech people) that it's a toy. Even the F-Droid description says: 

> You share a numeric key with your partner in real life and en/de-crypt some **important** messages with it.

https://f-droid.org/repository/browse/?fdid=dmusiolik.pijaret
(emphasis by me)

**Comment by MrFlyingToasterman** [comment]
@tdelmas Im going change the description in the next days.
As soon as F-Droid merged my request i'll close this issue.

**Comment by Natureshadow** [comment]
Really, please DO warn users that this is _only_ a nonsense toy. Please REALLY do, otherwise, your app is a dangerous anti-contribution to privacy education.

**Comment by Natureshadow** [comment]
Don't only warn on F-Droid. Update your README and place a popup on app start saying "This app is a toy - do NOT use for important communications!"

**Comment by MrFlyingToasterman** [comment]
@Natureshadow I do not want to harm anybody. Please see my current README.md

> Warning
> 
> Pijaret is just a small cipher and not for serious purpose.
> Please see my Schoolwork as a Toycrypter.
> The encryption is extremely weak.
> Read about ROT encryption: https://en.wikipedia.org/wiki/ROT13

But i can make a popup warning in the APP to.

I see this schoolproject is going way to far. It should just educate people not harm them.

**Comment by MrFlyingToasterman** [comment]
New Warnings in Description are merged.
See https://f-droid.org/repository/browse/?fdfilter=pijaret&fdid=dmusiolik.pijaret

And a Popup warning at the first start is now included.
