### ISSUE TITLE
how can use other character like arabic or persian?

### ISSUE THREAD

**Issue by armoun** [MrFlyingToasterman/Pijaret#7]
default use english character how i can change or plus other language?(UTF-8)
thank you @MrFlyingToasterman @licaon-kter

**Comment by MrFlyingToasterman** [comment]
Well i see...

Here is the Problem:

```
//deencrypt
    String uncipher(String input, int cryptvalue){
        String s = "";
        int len = input.length();

        for(int i = 0; i < len; i++) {
            char c = (char)(input.charAt(i) - cryptvalue);
            if (c > 'z') {
                s += (char)(input.charAt(i) + (27 + cryptvalue));
            }
            else {
                s += (char)(input.charAt(i) - cryptvalue);
            }
        }
        return s;
}
```

I'll try to get rid of this in this week.
But feel free to make a pull request if you can deal with the Problem before i can do.

Thanks for reporting!

**Comment by MrFlyingToasterman** [comment]
@armoun I'm shure it's fixed now. Sorry for the long waiting time.
